keys:
  # Users
  - &users:
    - &thestachelfisch BAD3CD149697F0C7B922824FACA965618087B276
  # Hosts
  - &hosts:
    - &framework age16uzpcjqa8mhqfcufzsq8gf66e9l34rv6dslt7s2r7h5td5d34eqq5nzuwd
    - &wsl age18cqhxtw6z7v4dap54swa66pvwep2wk32z30f5nfqzl74uxcmp4rslkkn5e
    - &malachite age1wgwxysjvqucy0a94aslwjpshftqagv66xjj0u0hx340ns2sjeevs70s2my

creation_rules:
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *framework
      - *wsl
      - *malachite
      pgp:
      - *thestachelfisch
  - path_regex: home/thestachelfisch/secrets.ya?ml$
    key_groups:
    - pgp:
      - *thestachelfisch
