keys:
  # Users
  - &users:
    - &stachel BAD3CD149697F0C7B922824FACA965618087B276
  # Hosts
  - &hosts:
    - &framework age1wl47l64jahksatswacx6sdyyc9g4r550g3qxp2605qt8ywtchv8sj04xu7

creation_rules:
  - path_regex: system/secrets.ya?ml$
    key_groups:
    - age:
      - *framework
      pgp:
      - *stachel
  - path_regex: home/stachel/secrets.ya?ml$
    key_groups:
    - pgp:
      - *stachel
