keys:
  # Users
  - &users:
    - &thestachelfisch BAD3CD149697F0C7B922824FACA965618087B276
  # Hosts
  - &hosts:
    - &desktop-computer age1jmadx7sru2r40gnvrlyz96808tq3mzctxfdtkx0j5uc3zhjn84qqhsdsta
    - &framework-laptop age1t2qmhjfgq2lpnn3ynapfj0689ultj9kwy4akad5vftn7knppv3dql82q3e

creation_rules:
  - path_regex: secrets/user-secrets\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *desktop-computer
      - *framework-laptop
      pgp:
      - *thestachelfisch
